"""Add column descriptions

Revision ID: 2bb22acdd00b
Revises: 53902a9d67be
Create Date: 2026-02-28 17:45:00.579722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb22acdd00b'
down_revision: Union[str, Sequence[str], None] = '53902a9d67be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataset_a33cb3cb_8f0a_484e_b73e_b695b30f8649')
    op.add_column('dataset_registry', sa.Column('column_descriptions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset_registry', 'column_descriptions')
    op.create_table('dataset_a33cb3cb_8f0a_484e_b73e_b695b30f8649',
    sa.Column('patient_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('residence', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sickle_cell_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('comorbidities', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_number_of_admissions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_of_admission_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_of_admission_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_of_admission_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_of_admission_4', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_of_admission_5', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('length_of_stay_for_each_admission_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('length_of_stay_for_each_admission_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('length_of_stay_for_each_admission_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('length_of_stay_for_each_admission_4', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('length_of_stay_for_each_admission_5', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interval_between_admissions_1_and_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interval_between_admissions_2_and_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interval_between_admissions_3_and_4', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interval_between_admissions_4_and_5', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('primary_reason_for_admission', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('treatment_given', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('outcome_of_admission', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hydroxyurea_use', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transfusion_history', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('if_yes,_how_many_units', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('complications', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
