"""Add registry

Revision ID: 350a155c8e4b
Revises: 0229d87c921c
Create Date: 2026-03-03 10:50:54.515344

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "350a155c8e4b"
down_revision: Union[str, Sequence[str], None] = "0229d87c921c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dataset_registry", sa.Column("column_types", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dataset_registry", "column_types")
    # ### end Alembic commands ###
