"""Add registry

Revision ID: 53902a9d67be
Revises: bcd70d758879
Create Date: 2026-02-28 17:33:50.522896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53902a9d67be'
down_revision: Union[str, Sequence[str], None] = 'bcd70d758879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_name')
    )
    op.create_index(op.f('ix_dataset_registry_file_hash'), 'dataset_registry', ['file_hash'], unique=True)
    op.create_index(op.f('ix_dataset_registry_original_filename'), 'dataset_registry', ['original_filename'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dataset_registry_original_filename'), table_name='dataset_registry')
    op.drop_index(op.f('ix_dataset_registry_file_hash'), table_name='dataset_registry')
    op.drop_table('dataset_registry')
    # ### end Alembic commands ###
