"""Add registry

Revision ID: e1be8c70526d
Revises: 693811a8ec49
Create Date: 2026-02-28 16:46:28.400538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1be8c70526d'
down_revision: Union[str, Sequence[str], None] = '693811a8ec49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_name')
    )
    op.create_index(op.f('ix_dataset_registry_file_hash'), 'dataset_registry', ['file_hash'], unique=True)
    op.create_index(op.f('ix_dataset_registry_original_filename'), 'dataset_registry', ['original_filename'], unique=False)
    op.drop_table('dataset_c8012a53_e5b4_4e25_b939_0edfbf4c1152')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_c8012a53_e5b4_4e25_b939_0edfbf4c1152',
    sa.Column('patient_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('residence', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sickle_cell_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('comorbidities', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_number_of_admissions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_of_admission_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_of_admission_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_of_admission_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_of_admission_4', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_of_admission_5', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('length_of_stay_for_each_admission_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('length_of_stay_for_each_admission_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('length_of_stay_for_each_admission_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('length_of_stay_for_each_admission_4', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('length_of_stay_for_each_admission_5', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interval_between_admissions_1_and_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interval_between_admissions_2_and_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interval_between_admissions_3_and_4', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interval_between_admissions_4_and_5', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('primary_reason_for_admission', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('treatment_given', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('outcome_of_admission', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hydroxyurea_use', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transfusion_history', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('if_yes,_how_many_units', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('complications', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_dataset_registry_original_filename'), table_name='dataset_registry')
    op.drop_index(op.f('ix_dataset_registry_file_hash'), table_name='dataset_registry')
    op.drop_table('dataset_registry')
    # ### end Alembic commands ###
